/**
 * @file appointments.type.ts
 * @summary Database table type definitions.
 */
import type { AppointmentSource, AppointmentStatus } from './dbEnums.type.js';

export type AppointmentsRow = {
    id: string,
    studio_id: string,
    client_id: string,
    booked_for_user_id: string | null,
    master_id: string,
    service_id: string,
    source: AppointmentSource,
    status: AppointmentStatus,
    attendee_name: string | null,
    attendee_phone_e164: string | null,
    attendee_email: string | null,
    client_comment: string | null,
    internal_comment: string | null,
    start_at: Date,
    end_at: Date,
    slot: string | null,
    price_amount: string,
    currency_code: string,
    created_by: string | null,
    updated_by: string | null,
    confirmed_at: Date | null,
    canceled_at: Date | null,
    completed_at: Date | null,
    transferred_at: Date | null,
    canceled_reason: string | null,
    deleted_at: Date | null,
    deleted_by: string | null,
    created_at: Date,
    updated_at: Date,
}

export type AppointmentsEntity = {
    id: string,
    studioId: string,
    clientId: string,
    bookedForUserId: string | null,
    masterId: string,
    serviceId: string,
    source: AppointmentSource,
    status: AppointmentStatus,
    attendeeName: string | null,
    attendeePhoneE164: string | null,
    attendeeEmail: string | null,
    clientComment: string | null,
    internalComment: string | null,
    startAt: Date,
    endAt: Date,
    slot: string | null,
    priceAmount: string,
    currencyCode: string,
    createdBy: string | null,
    updatedBy: string | null,
    confirmedAt: Date | null,
    canceledAt: Date | null,
    completedAt: Date | null,
    transferredAt: Date | null,
    canceledReason: string | null,
    deletedAt: Date | null,
    deletedBy: string | null,
    createdAt: Date,
    updatedAt: Date,
}

export type AppointmentsInsert = {
    studioId: string,
    clientId: string,
    bookedForUserId?: string | null,
    masterId: string,
    serviceId: string,
    source?: AppointmentSource,
    status?: AppointmentStatus,
    attendeeName?: string | null,
    attendeePhoneE164?: string | null,
    attendeeEmail?: string | null,
    clientComment?: string | null,
    internalComment?: string | null,
    startAt: Date,
    endAt: Date,
    priceAmount: string,
    currencyCode?: string,
    createdBy?: string | null,
    updatedBy?: string | null,
    confirmedAt?: Date | null,
    canceledAt?: Date | null,
    completedAt?: Date | null,
    transferredAt?: Date | null,
    canceledReason?: string | null,
    deletedAt?: Date | null,
    deletedBy?: string | null,
}

export type AppointmentsUpdate = Partial<{
    studioId: string,
    clientId: string,
    bookedForUserId: string | null,
    masterId: string,
    serviceId: string,
    source: AppointmentSource,
    status: AppointmentStatus,
    attendeeName: string | null,
    attendeePhoneE164: string | null,
    attendeeEmail: string | null,
    clientComment: string | null,
    internalComment: string | null,
    startAt: Date,
    endAt: Date,
    priceAmount: string,
    currencyCode: string,
    createdBy: string | null,
    updatedBy: string | null,
    confirmedAt: Date | null,
    canceledAt: Date | null,
    completedAt: Date | null,
    transferredAt: Date | null,
    canceledReason: string | null,
    deletedAt: Date | null,
    deletedBy: string | null,
}>
