export type MastersRow = {
    user_id: string,
    studio_id: string,
    display_name: string,
    bio: string | null,
    experience_years: number | null,
    procedures_done_total: number,
    rating_avg: string,
    rating_count: number,
    started_on: Date | null,
    materials_info: string | null,
    contact_phone_e164: string | null,
    contact_email: string | null,
    is_bookable: boolean,
    created_at: Date,
    updated_at: Date,
}

export type MastersEntity = {
    userId: string,
    studioId: string,
    displayName: string,
    bio: string | null,
    experienceYears: number | null,
    proceduresDoneTotal: number,
    ratingAvg: string,
    ratingCount: number,
    startedOn: Date | null,
    materialsInfo: string | null,
    contactPhoneE164: string | null,
    contactEmail: string | null,
    isBookable: boolean,
    createdAt: Date,
    updatedAt: Date,
}

export type MastersInsert = {
    userId: string,
    studioId: string,
    displayName: string,
    bio?: string | null,
    experienceYears?: number | null,
    proceduresDoneTotal?: number,
    ratingAvg?: string,
    ratingCount?: number,
    startedOn?: Date | null,
    materialsInfo?: string | null,
    contactPhoneE164?: string | null,
    contactEmail?: string | null,
    isBookable?: boolean,
}

export type MastersUpdate = Partial<{
    userId: string,
    studioId: string,
    displayName: string,
    bio: string | null,
    experienceYears: number | null,
    proceduresDoneTotal: number,
    ratingAvg: string,
    ratingCount: number,
    startedOn: Date | null,
    materialsInfo: string | null,
    contactPhoneE164: string | null,
    contactEmail: string | null,
    isBookable: boolean,
}>
